runtime: nodejs16
instance_class: F2
env_variables:
  NODE_ENV: "production"
beta_settings:
  cloud_sql_instances: "clinic-sql-db"
service_account: "1028517490288-compute@developer.gserviceaccount.com"
